version: '3.8'
services:
  # api:
  #   container_name: api
  #   build: .
  #   ports:
  #     - ${PORT}:${PORT}
  #   depends_on:
  #     - db
  #   volumes:
  #   - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes: 
 data: {}